<?php
$guest = $this->getGuestCollection();
$guestViewUrl = Mage::getUrl('guestbook/index/view');
?> 


<form action=" " method="post">
	<head>
		<h1>Form of back connecting</h1>
	</head>
	<label>your name
	<input name="Name" type="text" id="name_inputed" placeholder="input your name" size="30"></br></br></label>
	<label>your message</label>
	<textarea name="Message"  id="message_inputed"  cols="30" rows="10" placeholder="type your message to us" required></textarea></br>
	<input name="submitted" type="submit" value="Send"  onClick=""/></br></br>
</form>	

<?php foreach ($guest as $item): ?>
	<h2>
		<a href="<?php echo $guestViewUrl; ?>?id=<?php echo $item->getId(); ?>">
		<?php echo $item->getName(); ?>
		</a>
	</h2>
<?php endforeach; ?>
