<?php
$news = $this->getNewsCollection();
$newsViewUrl = Mage::getUrl('news/index/view');
?>
<h1>News6666666666666666666666666666666666666</h1>
<?php foreach ($news as $item): ?>
    <h2>
        <a href="<?php echo $newsViewUrl; ?> ?id=<?php echo $item->getId(); ?>">
            <?php echo $item->getTitle(); ?>
        </a>
    </h2>
<?php endforeach; ?>

<form>
	<input type="text" name="text">
	<textarea cols="40" rows="10"></textarea>
	<input type="submit">
	
</form>
